### ISSUE TITLE
How to start elasticsearch 7.0  in global mode in docker swarm?

### ISSUE THREAD

**Issue by shazChaudhry** [shazChaudhry/elastic#29]
I have posted a question in these forums:
1) https://discuss.elastic.co/t/how-to-start-elasticsearch-7-0-0-in-global-mode-in-a-docker-swarm-cluster/178712
2) https://stackoverflow.com/questions/55853969/how-to-deploy-elasticsearch-with-docker-swarm/55874149#55874149

**Comment by j-klemm** [comment]
Was this ever resolved? I am trying to do something similar.

**Comment by shazChaudhry** [comment]
Hi @j-klemm 
There is a suggestion in this stackoverflow that I have not tried yet: 
https://stackoverflow.com/questions/55853969/how-to-deploy-elasticsearch-with-docker-swarm/55874149#55874149

Please let me know if you manage to get it working.

**Comment by shazChaudhry** [comment]
@j-klemm - I have just tried v7.x in a swarm cluster of two nodes. I am pleased to say it is working. Here is my compose file: https://github.com/shazChaudhry/docker-elastic/blob/a49567673395e774510ea843d86074f1525d0fa4/docker-compose.yml

**Comment by j-klemm** [comment]
That is great, thank you for sharing!

**Comment by glafir** [comment]
`
















































































































































































































































































































































































































































































































































































































































































































































swarm.yml                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     

`version:` '3.7'
services:
  es-sr:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    hostname: "{{.Node.Hostname}}"
    environment:
      - node.name={{.Node.Hostname}}
      - cluster.name=sr-relef-cluster
      - discovery.seed_hosts=es-sr
      - cluster.initial_master_nodes=sr07,sr08,sr09
      - node.data=false
      - node.ingest=true
      - node.master=true
      - indices.requests.cache.size=70%
      - indices.queries.cache.size=10%
      - node.max_local_storage_nodes=3
      - node.ml=false
      - xpack.ml.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - bootstrap.memory_lock=false
      - ES_JAVA_OPTS=-Xms2024m -Xmx2024m
      - ES_PLUGINS_INSTALL=analysis-icu
    volumes:
      - hunspell-volume:/usr/share/elasticsearch/config/hunspell/
      - data01:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#      - 9300:9300
    networks:
      - elastic
    deploy:
#      placement:
#        constraints: [node.labels.app_role == es-sr]
      mode: global
      endpoint_mode: dnsrr
      resources:
        limits:
          memory: 3G

  es-sr-data:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    hostname: "{{.Node.Hostname}}"
    environment:
      - node.name={{.Node.Hostname}}-data
      - cluster.name=sr-relef-cluster
      - discovery.seed_hosts=es-sr
      - cluster.initial_master_nodes=sr07,sr08,sr09
      - node.data=true
      - node.master=false
      - node.ingest=true
      - indices.requests.cache.size=70%
      - indices.queries.cache.size=10%
      - node.max_local_storage_nodes=3
      - node.ml=false
      - xpack.ml.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - bootstrap.memory_lock=false
      - ES_JAVA_OPTS=-Xms2024m -Xmx2024m
      - ES_PLUGINS_INSTALL=analysis-icu
    volumes:
      - hunspell-volume:/usr/share/elasticsearch/config/hunspell/
      - data02:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#      - 9300:9300
    networks:
      - elastic
    deploy:
#      placement:
#        constraints: [node.labels.app_role == es-sr]
      mode: global
      endpoint_mode: dnsrr
      resources:
        limits:
          memory: 3G

  hunspell:
    image: gitlab.relef.ru:4567/glafir/hunspell-ru:latest
    depends_on:
      - es-sr
    networks:
      - elastic
    volumes:
      - hunspell-volume:/usr/share/elasticsearch/config/hunspell/
    entrypoint: sh
    deploy:
      mode: global
    tty: true

  nginx:
    image: nginx:alpine
    ports:
      - 9200:9200
    deploy:
      mode: global
    command: |
      /bin/sh -c "echo '
      user nobody nogroup;
      worker_processes auto;
      events {
        worker_connections 1024;
      }
      http {
        client_max_body_size 4g;
        resolver 127.0.0.11 ipv6=off;
        server {
          listen *:9200;
          location / {
            proxy_set_header Connection keep-alive;
            set $$url http://es-sr:9200;
            proxy_pass $$url;
            proxy_set_header  Host $$http_host;
            proxy_set_header  X-Real-IP $$remote_addr;
            proxy_set_header  X-Forwarded-For $$proxy_add_x_forwarded_for;
          }
        }
      }' | tee /etc/nginx/nginx.conf && nginx -t && nginx -g 'daemon off;'"
    networks:
      - elastic
volumes:
  data01:
    driver: local
  data02:
    driver: local
  hunspell-volume:

networks:
  elastic:
    driver: overlay
    attachable: true
`
Tree master and tree data node with nginx and hunspell
Injoy!

**Comment by glafir** [comment]
swarm.yml

```
version: '3.7'
services:
  es-sr:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    hostname: "{{.Node.Hostname}}"
    environment:
      - node.name={{.Node.Hostname}}
      - cluster.name=sr-relef-cluster
      - discovery.seed_hosts=es-sr
      - cluster.initial_master_nodes=sr07,sr08,sr09
      - node.data=false
      - node.ingest=true
      - node.master=true
      - indices.requests.cache.size=70%
      - indices.queries.cache.size=10%
      - node.max_local_storage_nodes=3
      - node.ml=false
      - xpack.ml.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - bootstrap.memory_lock=false
      - ES_JAVA_OPTS=-Xms2024m -Xmx2024m
      - ES_PLUGINS_INSTALL=analysis-icu
    volumes:
      - hunspell-volume:/usr/share/elasticsearch/config/hunspell/
      - data01:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#      - 9300:9300
    networks:
      - elastic
    deploy:
#      placement:
#        constraints: [node.labels.app_role == es-sr]
      mode: global
      endpoint_mode: dnsrr
      resources:
        limits:
          memory: 3G

  es-sr-data:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    hostname: "{{.Node.Hostname}}"
    environment:
      - node.name={{.Node.Hostname}}-data
      - cluster.name=sr-relef-cluster
      - discovery.seed_hosts=es-sr
      - cluster.initial_master_nodes=sr07,sr08,sr09
      - node.data=true
      - node.master=false
      - node.ingest=true
      - indices.requests.cache.size=70%
      - indices.queries.cache.size=10%
      - node.max_local_storage_nodes=3
      - node.ml=false
      - xpack.ml.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - bootstrap.memory_lock=false
      - ES_JAVA_OPTS=-Xms2024m -Xmx2024m
      - ES_PLUGINS_INSTALL=analysis-icu
    volumes:
      - hunspell-volume:/usr/share/elasticsearch/config/hunspell/
      - data02:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#      - 9300:9300
    networks:
      - elastic
    deploy:
#      placement:
#        constraints: [node.labels.app_role == es-sr]
      mode: global
      endpoint_mode: dnsrr
      resources:
        limits:
          memory: 3G

  hunspell:
    image: gitlab.relef.ru:4567/glafir/hunspell-ru:latest
    depends_on:
      - es-sr
    networks:
      - elastic
    volumes:
      - hunspell-volume:/usr/share/elasticsearch/config/hunspell/
    entrypoint: sh
    deploy:
      mode: global
    tty: true

  nginx:
    image: nginx:alpine
    ports:
      - 9200:9200
    deploy:
      mode: global
    command: |
      /bin/sh -c "echo '
      user nobody nogroup;
      worker_processes auto;
      events {
        worker_connections 1024;
      }
      http {
        client_max_body_size 4g;
        resolver 127.0.0.11 ipv6=off;
        server {
          listen *:9200;
          location / {
            proxy_set_header Connection keep-alive;
            set $$url http://es-sr:9200;
            proxy_pass $$url;
            proxy_set_header  Host $$http_host;
            proxy_set_header  X-Real-IP $$remote_addr;
            proxy_set_header  X-Forwarded-For $$proxy_add_x_forwarded_for;
          }
        }
      }' | tee /etc/nginx/nginx.conf && nginx -t && nginx -g 'daemon off;'"
    networks:
      - elastic
volumes:
  data01:
    driver: local
  data02:
    driver: local
  hunspell-volume:

networks:
  elastic:
    driver: overlay
    attachable: true
```

`docker stack deploy -c swarm.yml elastic`

Imjoy!
