### ISSUE TITLE
Deployment not working Host not found

### ISSUE THREAD

**Issue by prof-schacht** [shazChaudhry/elastic#31]
Hi,

I hope you can help me with the issue to get the version up and running. I used docker 18.06.3-ce  and followed your instruction to start up the environment. I changed the node1 entry in the environment variables to the host name of my swarm master. 

But I get the following error:
{"type": "server", "timestamp": "2019-11-18T09:25:15,179+0000", "level": "WARN", "component": "o.e.c.c.ClusterFormationFailureHelper", "cluster.name": "DevOps", "node.name": "vala-n6",  "message": "master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and this node must discover master-eligible nodes [vala-n1] to bootstrap a cluster: have discovered []; discovery will continue using [] from hosts providers and [{vala-n6}{40UudO_vSM-tjXJt69uBMQ}{fjbzNvJaTDSmDmLKbufmEA}{10.0.4.15}{10.0.4.15:9300}{ml.machine_memory=16691216384, xpack.installed=true, ml.max_open_jobs=20}] from last-known cluster state; node term 0, last-accepted version 0 in term 0"  }
{"type": "server", "timestamp": "2019-11-18T09:25:15,186+0000", "level": "WARN", "component": "o.e.d.SeedHostsResolver", "cluster.name": "DevOps", "node.name": "vala-n6",  "message": "failed to resolve host [elasticsearch]" ,

Also the Proxy produces the following error:
2019/11/18 09:37:54 Error: Fetching config from swarm listener failed: Get http://swarm-listener:8080/v1/docker-flow-swarm-listener/get-services: dial tcp: lookup swarm-listener on 127.0.0.11:53: no such host. Will retry in 5 seconds.

Did you have an idea what the issue could be and how  I can solve this. I have 6 nodes. Named vala-n1 to vala-n6.

BR and Thanks for your help.

**Comment by shazChaudhry** [comment]
@prof-schacht 
Sorry for the late response. I have been away and so was not able to look at the issue. Thank for creating this issue. I will get back to you as soon as I can.

**Comment by shazChaudhry** [comment]
@prof-schacht 
Have you been able to fix your issue or are you still getting the error?

**Comment by shazChaudhry** [comment]
closing this issue as there is no user interaction
