### ISSUE TITLE
Unsupported config option for services.filebeat: 'configs'

### ISSUE THREAD

**Issue by k8scat** [shazChaudhry/elastic#32]

**Comment by k8scat** [comment]
ERROR: The Compose file './docker-compose.yml' is invalid because:
Invalid top-level property "configs". Valid top-level sections for this Compose file are: version, services, networks, volumes, and extensions starting with "x-".

You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
Unsupported config option for services.filebeat: 'configs'

**Comment by shazChaudhry** [comment]
@hsowan-me  
I have never come across this error but thanks for pointing this out. I will take a look.

- What version of docker are you using?

**Comment by shazChaudhry** [comment]
@hsowan-me 
Have you been able to fix your issue or are you still getting the error? I am not getting the error that you have reported.

Out of curiosity,  are you trying to stand the stack up by running docker-compose or docker swarm?

**Comment by shazChaudhry** [comment]
closing this issue as there is no user interaction.
