### ISSUE TITLE
Using https connexions don't work 

### ISSUE THREAD

**Issue by belfo** [shazChaudhry/elastic#38]
Hello,

In the process of upgrading the elk stack from 6.X to 7.X i tried to follow your config, using dnsrr (to avoid issue with the ingress address)
The cluster seems up, (i can curl from the elastic container)
But other service can't access it (like kibana)

I use authentication for the connection, passing by the https. Did you try with it?

Regards

**Comment by shazChaudhry** [comment]
In this repo I only test with "HTTP" protocol

for HTTPS protocol, you might find this [blog](https://www.elastic.co/blog/configuring-ssl-tls-and-https-to-secure-elasticsearch-kibana-beats-and-logstash) useful.

- https://www.elastic.co/blog/configuring-ssl-tls-and-https-to-secure-elasticsearch-kibana-beats-and-logstash

**Comment by belfo** [comment]
I have already ssl on 6.X without issue. Is the upgrade to 7.X that cause an issue as we can't use the discovery zen.
was looking to a solution to this

**Comment by shazChaudhry** [comment]
Please accept my apologies that I am not able to help. 
HTTPS is not in scope of this repo and I have done no testing with HTTPS in this repo.

**Comment by belfo** [comment]
No problem was just a question :) thx for the time

**Comment by belfo** [comment]
Founded the issue. Was not related to SSL, but to dnsrr.
I don't have elasticsearch on every node of swarm, and the service was not visible from nodes where elasticsearch is not running, even if connected to network.
I found some issue on swarm about network and dnsrr

**Comment by shazChaudhry** [comment]
very please to hear you managed you resolve the issue.
