### ISSUE TITLE
How to add elastic cluster monitoring the right way? 

### ISSUE THREAD

**Issue by jinnabaalu** [shazChaudhry/elastic#42]
I have tried with the below module configuration. 

```bash

metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ['elasticsearch:9200'] # Moonitoring cluster
  protocol: "http"

setup.kibana:
  host: "http://kibana:5601/monitoringkibana" #Monitoring KIbana
  protocol: "http"
  ssl.enabled: false
  
xpack.monitoring.enabled: true
setup.dashboards.enabled: true

metricbeat.modules:
- module: elasticsearch
  metricsets:
    - node
    - node_stats
    - index
    - index_summary
    - shard
  period: 20s
  hosts: ["http://192.168.0.1:9201"] #Production Elasticseaarch which I want to create monitoring for
```

I am getting only OS analytics

**Comment by shazChaudhry** [comment]
Hi @JinnaBalu. What you are asking is not part of my architecture and so unfortunately, I will not be able to replicate your issue.

If you are just after elasticsearch metrics, I do not believe you need this configuration file at all. Kibana provides stack monitoring capability out of the  box:

Kibana -> Management -> [Stack Monitoring](https://github.com/shazChaudhry/docker-elastic/blob/master/pics/Screenshot%202020-10-16%20at%2019.41.49.png). On this page you can click on nodes to various links to get the metrics.

Hope this was helpful.

**Comment by shazChaudhry** [comment]
No user activity on this issue and so it is being closed
